// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Confetti","status":true,"description":"","parameters":{}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"OpheliaEnigma_FullscreenResolution","status":true,"description":"Allows the developer to set a specific resolution throughout the game\r\nand start it in fullscreen.","parameters":{"width":"1280","height":"720"}},
{"name":"YEP_MessageCore","status":true,"description":"v1.19 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"1024","Face Indent":"Window_Base._faceWidth + 24","Fast Forward Key":"pagedown","Enable Fast Forward":"true","Word Wrapping":"false","Description Wrap":"false","Word Wrap Space":"false","Tight Wrap":"false","---Font---":"","Font Name":"GameFont","Font Name CH":"SimHei, Heiti TC, sans-serif","Font Name KR":"Dotum, AppleGothic, sans-serif","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","Font Outline":"4","Maintain Font":"false","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]","Name Box Auto Close":"false"}},
{"name":"ChoiceOffset","status":true,"description":"調整選擇項目視窗與螢幕邊緣的距離","parameters":{"Offset X":"128"}},
{"name":"ShowPlayerScore","status":true,"description":"顯示角色名稱與分數（名稱靠左、分數靠右，手動控制）v1.4","parameters":{}},
{"name":"ShowFloatingScore","status":true,"description":"顯示浮動文字（玩家或事件頭上，手動控制顯示／立即移除）v1.0","parameters":{}},
{"name":"ShowFirework","status":true,"description":"","parameters":{}},
{"name":"ExitCommand","status":true,"description":"在主選單新增「退出遊戲」選項，按下即可關閉遊戲","parameters":{}}
];
